[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
panic-abort-tests = true

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[build]
target = "x86_64-fluksos.json"